### ISSUE TITLE
Decompiling problem.

### ISSUE THREAD

**Issue by ShadowsAdi** [Headline/Lysis-Web#5]
Hello,
After the update, the decompiling is not working too good.
https://imgur.com/a/dja9W4b
On files bigger, it shows only some piece of code.
EDIT: I saw that it decompiles very slowly, 5 minutes later, it shows me two more arrays.

**Comment by Headline** [comment]
I'll look into this; in the meantime I'll go ahead and remove syntax highlighting on code output
