### ISSUE TITLE
Anoher lysis version with bypass all errors and protections

### ISSUE THREAD

**Issue by UnrealKaraulov** [Headline/Lysis-Web#6]
@Headline hello! You can add to website also another version of lysis ? (switch between two versions)

My fork can bypass all known protections (AMXX) : https://github.com/UnrealKaraulov/lysis-java

**Comment by Headline** [comment]
Hello!

If you can get your changes into peace-maker's I would happily update, but will not support running any forks.

Fell free to host your own that can!

Thanks

**Comment by UnrealKaraulov** [comment]
@Headline this can crack original features, because many strange changes. Peace-makers not allowed this pr)))

**Comment by UnrealKaraulov** [comment]
@Headline for adding version switch need more than 10 lines of code?)
